---

appservers:
    hosts:
      frontend-vm:
        ansible_host: frontend-gcloud
      gcloud-app-server:
        ansible_host: backend-gcloud
      
dbservers:
    hosts:
      azure-db-server:
          ansible_host: database-azure