---
- hosts: all
  become: yes
  
  tasks:
    - name: Check if Docker is installed
      shell: docker --version && docker compose version
      register: docker_version_result
      ignore_errors: true

    - name: Set Docker installed fact
      set_fact:
        docker_installed: "{{ docker_version_result.rc == 0 }}"

    - name: Include and run the Docker playbook if Docker is not installed
      import_tasks: docker.yaml
      when: not docker_installed
      register: docker_output
      ignore_errors: no
      
    - name: Show Docker playbook output
      debug:
        var: docker_output.stdout
      when: not docker_installed

    - name: "Clone the Spring repository"
      git:
        repo: "https://github.com/AlexandrosManolis/farmerCompensation.git"
        dest: "{{ appdir }}"
        version: "{{ branch }}"
        force: yes

    - name: Tear down existing services
      community.docker.docker_compose:
        project_src: "{{ appdir }}"
        state: absent

    - name: Create and start services
      docker_compose:
        project_src: "{{ appdir }}"
        build: true
        state: present
      register: output
      notify: Restart Docker Compose

    - debug:
        var: output

  handlers:
    - name: Restart Docker Compose
      community.docker.docker_compose:
        project_src: "{{ appdir }}"
        restarted: true